version: '3.8'

services:
  database:
    container_name: password_manager-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./config/packages/dev/docker/mysql/db:/var/lib/mysql
  php:
    container_name: password_manager-php
    build:
      context: ./config/packages/dev/docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./config/packages/dev/docker/php/app:/var/www/password_manager
    depends_on:
      - database
  nginx:
    container_name: password_manager-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./config/packages/dev/docker/nginx/app:/var/www/password_manager
      - ./config/packages/dev/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - password_manager-php
      - password_manager-database
