version: '3.9'

services:
  db:
    container_name: password-manager_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password_manager
    ports:
      - '${MYSQL_HOST_PORT}:3306'
    volumes:
      - ./config/packages/dev/docker/mysql/db:/var/lib/mysql
    networks:
      - default
  php:
    container_name: password-manager_php
    build:
      context: ./config/packages/dev/docker/php
      args:
        # Pass down environment variables as arguments for the Dockerfile.
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_EMAIL=${GITHUB_EMAIL}
        - SYSTEM_UID=${SYSTEM_UID}
        - XDEBUG_HOST_PORT=${XDEBUG_HOST_PORT}
    ports:
      - '${PHP_FASTCGI_HOST_PORT}:9000'
    volumes:
      - ./:/var/www/password-manager
      - ./config/packages/dev/docker/php/php-fpm.d/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./config/packages/dev/docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/packages/dev/docker/php/conf.d/docker-php-ext-debug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      - default
  nginx:
    container_name: password-manager_nginx
    image: nginx:1.20.0-alpine
    ports:
      - '${NGINX_HTTP_HOST_PORT}:80'
      - '${NGINX_HTTPS_HOST_PORT}:443'
    volumes:
      - ./:/var/www/password-manager
      - ./config/packages/dev/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/packages/dev/docker/nginx/api.dev.local.crt:/etc/ssl/certs/dev.local.crt
      - ./config/packages/dev/docker/nginx/api.dev.local.key:/etc/ssl/private/dev.local.key
      - ./config/packages/dev/docker/nginx/dhparam.pem:/etc/nginx/dhparam.pem
    depends_on:
      - php
      - db
    networks:
      - default
networks:
  # Single network for all three services.
  default:
    name: password-manager_network
    driver: bridge
