version: '3.9'

services:
  mysql:
    container_name: vaults_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaults
    ports:
      - '${MYSQL_HOST_PORT}:3306'
    volumes:
      - ./mysql/db:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
  php:
    container_name: vaults_php
    build:
      context: ./php
      args:
        # Pass down environment variables as arguments for the Dockerfile.
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_EMAIL=${GITHUB_EMAIL}
        - SYSTEM_UID=${SYSTEM_UID}
        - XDEBUG_HOST_PORT=${XDEBUG_HOST_PORT}
    ports:
      - '${PHP_FASTCGI_HOST_PORT}:9000'
    volumes:
      - ../api/:/var/www/vaults_api
      - ./php/php-fpm.d/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf.d/docker-php-ext-debug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mysql
    networks:
      - default
  nginx:
    container_name: vaults_nginx
    image: nginx:1.20.0-alpine
    ports:
      - '${SERVER_HTTP_HOST_PORT}:80'
      - '${SERVER_HTTPS_HOST_PORT}:443'
    volumes:
      - ../api/:/var/www/vaults_api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/password-manager.crt:/etc/ssl/certs/password-manager.crt
      - ./nginx/password-manager.key:/etc/ssl/private/password-manager.key
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
    depends_on:
      - php
      - mysql
    networks:
      - default
  vue:
    container_name: vaults_vue
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - '${SPA_HTTPS_HOST_PORT}:1024'
    volumes:
      - ../frontend/:/var/www/vaults_frontend/
    depends_on:
      - php
networks:
  # Single network for all three services.
  default:
    name: vaults_network
    driver: bridge
