index:
  path: /
  controller: App\Controller\DefaultController::index

register:
  path: /register
  controller: App\Controller\RegistrationController:register

login:
  path: /user/login
  controller: App\Controller\SecurityController:login

logout:
  path: /user/logout
  controller: App\Controller\SecurityController:logout

profile:
  path: /user/profile
  controller: App\Controller\SecurityController:profile
