index:
  path: /
  controller: App\Controller\DefaultController::index

register:
  path: /register
  controller: App\Controller\RegistrationController:register

login:
  path: /login

logout:
  path: /logout

profile:
  path: /user/profile
  controller: App\Controller\UserController:profile

vaults:
  path: /vaults
  controller: App\Controller\VaultController:list

vaults_create:
  path: /vaults/create
  controller: App\Controller\VaultController::create

vaults_update:
  path: /vaults/update/{id}
  controller: App\Controller\VaultController::update
  requirements:
    id: '\d+'

vaults_delete:
  path: /vaults/delete/{id}
  controller: App\Controller\VaultController::delete
  requirements:
    id: '\d+'

vaults_items:
  path: /vaults/{id}/{userId}
  controller: App\Controller\VaultController::listItems
  requirements:
    id: '\d+'
    userId: '\d+'

logins_create:
  path: /logins/create
  controller: App\Controller\LoginController::create

logins_update:
  path: /logins/update/{id}
  controller: App\Controller\LoginController::update
  requirements:
    id: '\d+'

logins_delete:
  path: /logins/delete/{id}
  controller: App\Controller\LoginController::delete
  requirements:
    id: '\d+'

note_create:
  path: /note/create
  controller: App\Controller\NoteController::create

note_update:
  path: /note/update/{id}
  controller: App\Controller\NoteController::update
  requirements:
    id: '\d+'

note_delete:
  path: /note/delete/{id}
  controller: App\Controller\NoteController::delete
  requirements:
    id: '\d+'
