index:
  path: /
  controller: App\Controller\DefaultController::index

authentication_register:
  path: /authentication/register
  controller: App\Controller\RegistrationController:register

authentication_login:
  path: /authentication/login

authentication_logout:
  path: /authentication/logout

vaults:
  path: /vaults
  controller: App\Controller\VaultController:list
  methods: ["GET"]

vaults_create:
  path: /vaults
  controller: App\Controller\VaultController::create
  methods: ["POST"]

vaults_update:
  path: /vaults/{id}
  controller: App\Controller\VaultController::update
  requirements:
    id: '\d+'
  methods: ["PUT"]

vaults_delete:
  path: /vaults/{id}
  controller: App\Controller\VaultController::delete
  requirements:
    id: '\d+'
  methods: ["DELETE"]

vaults_items:
  path: /vaults/{id}/items
  controller: App\Controller\VaultController::listItems
  requirements:
    id: '\d+'
    userId: '\d+'
  methods: ["GET"]

logins_create:
  path: /logins/create
  controller: App\Controller\LoginController::create

logins_update:
  path: /logins/update/{id}
  controller: App\Controller\LoginController::update
  requirements:
    id: '\d+'

logins_delete:
  path: /logins/delete/{id}
  controller: App\Controller\LoginController::delete
  requirements:
    id: '\d+'

note_create:
  path: /note/create
  controller: App\Controller\NoteController::create

note_update:
  path: /note/update/{id}
  controller: App\Controller\NoteController::update
  requirements:
    id: '\d+'

note_delete:
  path: /note/delete/{id}
  controller: App\Controller\NoteController::delete
  requirements:
    id: '\d+'

category:
  path: /category
  controller: App\Controller\CategoryController:list
  methods: ["GET"]

category_create:
  path: /category
  controller: App\Controller\CategoryController::create
  methods: ["POST"]

category_update:
  path: /category/{id}
  controller: App\Controller\CategoryController::update
  requirements:
    id: '\d+'
  methods: ["PUT"]

category_delete:
  path: /category/{id}
  controller: App\Controller\CategoryController::delete
  requirements:
    id: '\d+'
  methods: ["DELETE"]

category_items:
  path: /category/{id}/items
  controller: App\Controller\CategoryController::listItems
  requirements:
    id: '\d+'
  methods: ["GET"]
